[package]
name = "template"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
imageproc = "0.22.0"
image = "0.23.14"
enigo = "0.0.14"
scrap = "0.5"
arrayfire = "3.8.0"